CREATE TABLE DRIVERSLICENSE (
    LICENSENO VARCHAR2(12) NOT NULL,
    LASTNAME VARCHAR2(255) NOT NULL,
    FIRSTNAME VARCHAR2(255) NOT NULL,
    DOB DATE,
    ISSUEDATE DATE,
    EXPDATE DATE,
    GENDER CHAR(1),
    LICENSECLASS CHAR(1),
    ADDRESS VARCHAR2(255),
    CONSTRAINT DRIVERSLICENSE_PK PRIMARY KEY (LICENSENO)
);

CREATE TABLE VEHICLE (
    VIN VARCHAR2(17) NOT NULL,
    MANUFACTURER VARCHAR2(50),
    MODEL VARCHAR2(20),
    YEAR NUMBER(2),
    CONSTRAINT VEHICLE_PK PRIMARY KEY (VIN)
);

CREATE TABLE AUTOINSURANCE (
    POLICYNO VARCHAR2(20) NOT NULL,
    LICENSENO VARCHAR2(12) NOT NULL,
    VIN VARCHAR2(17) NOT NULL,
    ANNUALPREMIUM NUMBER(7,2),
    PAYMENT CHAR(1),
    PAYMENTINSTITUTION VARCHAR2(50),
    CONSTRAINT AUTOINSURANCE_PK PRIMARY KEY (POLICYNO),
    CONSTRAINT AUTOINSURANCE_LICENSENO_FK FOREIGN KEY (LICENSENO) REFERENCES DRIVERSLICENSE(LICENSENO),
    CONSTRAINT AUTOINSURANCE_VIN_FK FOREIGN KEY (VIN)REFERENCES VEHICLE(VIN)
);
    
ALTER TABLE DRIVERSLICENSE
ADD CONSTRAINT CHECK_GENDER
CHECK (GENDER IN ('F', 'M'))


ALTER TABLE DRIVERSLICENSE 
ADD CONSTRAINT CHECK_LICENSECLASS 
CHECK (LICENSECLASS IN ('G', 'G1', 'G2', 'M', 'M1', 'M2', 'A', 'B', 'C', 'D', 'E', 'F'));


ALTER TABLE DRIVERSLICENSE 
ADD CONSTRAINT CHECK_ISSUE_EXPDATE 
CHECK (ISSUEDATE < EXPDATE);

ALTER TABLE AUTOINSURANCE
ADD CONSTRAINT CHECK_PAYMENT
CHECK (PAYMENT IN ('M', 'A'));

ALTER TABLE AUTOINSURANCE
ADD (POLSTARTDATE DATE,
    POLENDDATE DATE,
    POLOWNER VARCHAR2(255));
    
/* I would add a constraint AUTOINSURANCE to make sure that POLSTARTDATE is earlier than POLENDDATE, 
but left out due to instructions not requiring it.
The statement would look like so:
ALTER TABLE AUTOINSURANCE
ADD CONSTRAINT CHECK_POLDATE
CHECK (POLSTARTDATE < POLENDDATE));
*/


ALTER TABLE VEHICLE
ADD (
    VEHICLE_TYPE VARCHAR2(5),
    COLOR VARCHAR2(20),
    LICENSE_PLATE_NO VARCHAR2(6),
    REGISTRATION_EXPIRY DATE,
    CONSTRAINT VEHICLE_TYPE_CHECK CHECK (VEHICLE_TYPE IN ('Car', 'SUV', 'Truck', 'Van')),
    CONSTRAINT LICENSE_PLATE_NO_UNIQUE UNIQUE (LICENSE_PLATE_NO)
);

INSERT ALL 
    INTO DRIVERSLICENSE (LICENSENO, LASTNAME, FIRSTNAME, DOB, ISSUEDATE, EXPDATE, GENDER, LICENSECLASS, ADDRESS) 
    VALUES ('D1234567890', 'Smith', 'John', TO_DATE('1985-06-15', 'YYYY-MM-DD'), TO_DATE('2005-08-20', 'YYYY-MM-DD'), TO_DATE('2025-08-20', 'YYYY-MM-DD'), 'M', 'A', '123 Elm St, London')
    INTO DRIVERSLICENSE (LICENSENO, LASTNAME, FIRSTNAME, DOB, ISSUEDATE, EXPDATE, GENDER, LICENSECLASS, ADDRESS) 
    VALUES ('D0987654321', 'Johnson', 'Emily', TO_DATE('1990-02-20', 'YYYY-MM-DD'), TO_DATE('2010-09-15', 'YYYY-MM-DD'), TO_DATE('2030-09-15', 'YYYY-MM-DD'), 'F', 'G', '456 Oak Rd, Toronto')
    INTO DRIVERSLICENSE (LICENSENO, LASTNAME, FIRSTNAME, DOB, ISSUEDATE, EXPDATE, GENDER, LICENSECLASS, ADDRESS) 
    VALUES ('D1122334455', 'Brown', 'Michael', TO_DATE('1978-11-03', 'YYYY-MM-DD'), TO_DATE('2000-01-25', 'YYYY-MM-DD'), TO_DATE('2025-01-25', 'YYYY-MM-DD'), 'M', 'M', '789 Pine Blvd, Kitchener')
    INTO DRIVERSLICENSE (LICENSENO, LASTNAME, FIRSTNAME, DOB, ISSUEDATE, EXPDATE, GENDER, LICENSECLASS, ADDRESS) 
    VALUES ('D2233445566', 'Davis', 'Sarah', TO_DATE('1982-09-10', 'YYYY-MM-DD'), TO_DATE('2008-03-12', 'YYYY-MM-DD'), TO_DATE('2028-03-12', 'YYYY-MM-DD'), 'F', 'D', '101 Maple Dr, Waterloo')
SELECT 1 FROM DUAL;



INSERT ALL 
    INTO VEHICLE (VIN, MANUFACTURER, MODEL, YEAR, VEHICLE_TYPE, COLOR, LICENSE_PLATE_NO, REGISTRATION_EXPIRY) 
    VALUES ('1HGCM82633A123456', 'Honda', 'Civic', 23, 'Car', 'Blue', 'ABC123', TO_DATE('2026-06-15', 'YYYY-MM-DD'))
    INTO VEHICLE (VIN, MANUFACTURER, MODEL, YEAR, VEHICLE_TYPE, COLOR, LICENSE_PLATE_NO, REGISTRATION_EXPIRY) 
    VALUES ('1FTRX18W9XKA12345', 'Ford', 'F-150', 22, 'Truck', 'Red', 'DEF456', TO_DATE('2025-08-20', 'YYYY-MM-DD'))
    INTO VEHICLE (VIN, MANUFACTURER, MODEL, YEAR, VEHICLE_TYPE, COLOR, LICENSE_PLATE_NO, REGISTRATION_EXPIRY) 
    VALUES ('2T1BURHE6GC123456', 'Toyota', 'Corolla', 21, 'Car', 'Black', 'GHI789', TO_DATE('2024-12-01', 'YYYY-MM-DD'))
    INTO VEHICLE (VIN, MANUFACTURER, MODEL, YEAR, VEHICLE_TYPE, COLOR, LICENSE_PLATE_NO, REGISTRATION_EXPIRY) 
    VALUES ('3N1AB7AP8HY123456', 'Nissan', 'Sentra', 24, 'SUV', 'White', 'JKL123', TO_DATE('2027-01-10', 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;



INSERT ALL 
    INTO AUTOINSURANCE (POLICYNO, LICENSENO, VIN, ANNUALPREMIUM, PAYMENT, PAYMENTINSTITUTION, POLSTARTDATE, POLENDDATE, POLOWNER) 
    VALUES ('POL12345', 'D1234567890', '1HGCM82633A123456', 1200.50, 'M', 'State Farm', TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'John Smith')
    INTO AUTOINSURANCE (POLICYNO, LICENSENO, VIN, ANNUALPREMIUM, PAYMENT, PAYMENTINSTITUTION, POLSTARTDATE, POLENDDATE, POLOWNER) 
    VALUES ('POL23456', 'D0987654321', '1FTRX18W9XKA12345', 950.75, 'M', 'Geico', TO_DATE('2023-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'Emily Johnson')
    INTO AUTOINSURANCE (POLICYNO, LICENSENO, VIN, ANNUALPREMIUM, PAYMENT, PAYMENTINSTITUTION, POLSTARTDATE, POLENDDATE, POLOWNER) 
    VALUES ('POL34567', 'D1122334455', '2T1BURHE6GC123456', 12400.00, 'A', 'Progressive', TO_DATE('2023-08-15', 'YYYY-MM-DD'), TO_DATE('2024-08-15', 'YYYY-MM-DD'), 'Michael Brown')
    INTO AUTOINSURANCE (POLICYNO, LICENSENO, VIN, ANNUALPREMIUM, PAYMENT, PAYMENTINSTITUTION, POLSTARTDATE, POLENDDATE, POLOWNER) 
    VALUES ('POL45678', 'D2233445566', '3N1AB7AP8HY123456', 13100.40, 'A', 'Allstate', TO_DATE('2023-09-01', 'YYYY-MM-DD'), TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'Sarah Davis')
SELECT 1 FROM DUAL;



